# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0f76a3c461f0e77e8ecf7e9afdeda4b"
name = "Factory Engine Eagle DTF Print"
application_url = "https://api.eagledtfprint.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_inventory,read_orders,read_products,read_shipping,read_themes,write_content,write_customers,write_discounts,write_inventory,write_orders,write_price_rules,write_products,write_shipping,write_themes"

[auth]
redirect_urls = [
  "https://api.eagledtfprint.com/api/v1/auth/shopify/callback",
  "https://api.eagledtfprint.com/api/auth/shopify/callback",
  "https://app.eagledtfprint.com/api/auth/callback"
]
