# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0f76a3c461f0e77e8ecf7e9afdeda4b"
name = "Factory Engine Eagle DTF Print"
application_url = "https://api.eagledtfprint.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes,read_content,write_content,read_inventory,write_inventory,read_shipping,write_shipping,write_price_rules,write_discounts"

[auth]
redirect_urls = [
  "https://api.eagledtfprint.com/api/v1/auth/shopify/callback",
  "https://api.eagledtfprint.com/api/auth/shopify/callback",
  "https://app.eagledtfprint.com/api/auth/callback"
]
